# Termos que o robô vai buscar nos diários
termos_monitorados:
  - "OAB/SP 123456"
  - "SEU NOME COMPLETO"
  - "00.000.000/0001-00"


# Configurações do Robô FIO

webhook_url: "https://webhook.site/d7543f9f-ddf6-4e12-81f7-bd2138da1008"  

termos_busca:
  - '"OAB/SP"'
  - '"Aquisição de Computadores"'
  - '"Aquisição de Computadores"'
limite_por_termo: 2   # Baixo para o teste ser rápido